name: .NET Core

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
<<<<<<< HEAD:.github/workflows/ci.yml
    - uses: toolmantim/release-drafter@v5.2.0
      name: Draft
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
=======
>>>>>>> master:.github/workflows/dotnet-core-test.yml
