name: CI (.NET Core)

on: [push, pull_request, workflow_dispatch]

env:
  PR_PROMPT: "::warning:: Build artifact will not be uploaded due to the workflow is trigged by pull request."

jobs:
  build:
    name: Build binary CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.302
    - name: Initialize Submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      env:
        IS_PR: ${{ !!github.head_ref }}
      run: |
        if $IS_PR ; then echo $PR_PROMPT; fi
        dotnet build --configuration Release --no-restore
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      if: ${{ !github.head_ref }}
      with:
        name: windows_amd64
        path: bin/net6.0/
    - uses: toolmantim/release-drafter@v5.2.0
      name: Draft
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
